apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-{{ .Values.apptype }}-{{ .Values.appname }}
  name: deployment-{{ .Values.apptype }}-{{ .Values.appname }}
  labels:
    app: app-{{ .Values.apptype }}-{{ .Values.appname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-{{ .Values.apptype }}-{{ .Values.appname }}
  template:
    metadata:
      labels:
        app: app-{{ .Values.apptype }}-{{ .Values.appname }}
    spec:
      containers:
      - name: cnt-nginx
        image: phpmyadmin:5.2.3
        ports:
        - containerPort: 80
        env:
        - name: PMA_ARBITRARY
          value: "1"