apptype: resizer

appname: app1

storageclass-lin: linode-block-storage-retain

storageclass-k3s: local-path

storageclass: local-path

storageclass-oci: oci-bv
storageclass-ovh1: csi-cinder-classic
storageclass-ovh2: csi-cinder-high-speed
storageclass-ovh3: csi-cinder-high-speed-gen2

pvcstorage: 80Gi

mainimage: registry1.host247.org/picdepo-resizer:v22
#mainimage: nginx