apptype: mariadb

appname: app1

storageclass: vultr-block-storage-hdd

storageclass-do: do-block-storage

storageclass-k3s: local-path

pvcstorage: 40Gi

nodePort: 30096

mysqlrootpassword: mariadbvultrc179780g543278JKJKGYFQXPVJHoiwiodfsertAPOOQAMU

image: mariadb:12