apiVersion: apps/v1
kind: Deployment
metadata:
  name: externals1
  namespace: externals
  labels:
    app: externals-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: externals
  template:
    metadata:
      labels:
        app: externals
    spec:
      containers:
      - name: apche2
        image: httpd:2.4